services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: backend
    build: backend
    command: sh -c 'alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --app-dir src'
    volumes:
      - ./backend:/app
      # - ./.docker/.ipython:/root/.ipython
    environment:
      # PYTHONPATH: .
      DATABASE_URL: postgresql+asyncpg://postgres:TODO_CHANGE_ME@postgres:5432/postgres
    depends_on:
      - postgres

  frontend:
    image: frontend
    build:
      context: frontend
      target: development
    # for bind node_modules
    # command: sh -c '[ "$$(ls -A node_modules)" ] && yarn start || yarn && yarn start'
    volumes:
      # for bind node_modules
      # - ./frontend/node_modules:/app/node_modules
      # for volume node_modules
      # - node_modules:/app/node_modules
      - ./frontend/src:/app/src

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: TODO_CHANGE_ME
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
  # for volume node_modules (PWD => global_path)
  # node_modules:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: $PWD/frontend/node_modules
