services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: backend
    build: backend
    command: sh -c 'alembic upgrade head && python ./src/db/init_db.py && gunicorn src.main:app -b 0.0.0.0 -w 4 -k uvicorn.workers.UvicornWorker'
    volumes:
      - ./backend/:/app/:ro
    env_file:
      - .env
    # depends_on:
    #   - postgres

  frontend:
    image: builder
    build:
      context: frontend
      target: builder
    volumes:
      - dist:/app/dist/


volumes:
  db-data:
  dist:
